import {
  createAppleSplashScreens,
  defineConfig,
} from "@vite-pwa/assets-generator/config";

export default defineConfig({
  headLinkOptions: {
    preset: "default",
    basePath: "/pictures/",
    xhtml: true,
  },
  preset: {
    png: {
      force: true,
      compressionLevel: 9,
      progressive: true,
      palette: true,
      adaptiveFiltering: true,
      quality: 60,
    },
    assetName: (type, size) => `${type}-icon-${size.width}x${size.height}.png`,
    appleSplashScreens: createAppleSplashScreens({
      padding: 0.3,
      resizeOptions: { fit: "contain", background: "#2E3440" },
      darkResizeOptions: { fit: "contain", background: "#2E3440" },
      linkMediaOptions: {
        log: true,
        addMediaScreen: true,
        xhtml: true,
        basePath: "/pictures/",
      },
    }),
    apple: {
      sizes: [
        { width: 32, height: 32 },
        { width: 40, height: 40 },
        { width: 58, height: 58 },
        { width: 60, height: 60 },
        { width: 64, height: 64 },
        { width: 76, height: 76 },
        { width: 80, height: 80 },
        { width: 87, height: 87 },
        { width: 120, height: 120 },
        { width: 152, height: 152 },
        { width: 167, height: 167 },
        { width: 180, height: 180 },
        { width: 192, height: 192 },
        { width: 512, height: 512 },
        { width: 1024, height: 1024 },
      ],
      resizeOptions: { fit: "contain", background: "#2E3440" },
    },
    transparent: {
      sizes: [
        { width: 40, height: 40 },
        { width: 58, height: 58 },
        { width: 60, height: 60 },
        { width: 64, height: 64 },
        { width: 76, height: 76 },
        { width: 80, height: 80 },
        { width: 87, height: 87 },
        { width: 120, height: 120 },
        { width: 152, height: 152 },
        { width: 167, height: 167 },
        { width: 180, height: 180 },
        { width: 192, height: 192 },
        { width: 512, height: 512 },
        { width: 1024, height: 1024 },
      ],
      resizeOptions: { fit: "contain", background: "#2E3440" },
    },
    maskable: {
      sizes: [
        { width: 40, height: 40 },
        { width: 58, height: 58 },
        { width: 60, height: 60 },
        { width: 64, height: 64 },
        { width: 76, height: 76 },
        { width: 80, height: 80 },
        { width: 87, height: 87 },
        { width: 120, height: 120 },
        { width: 152, height: 152 },
        { width: 167, height: 167 },
        { width: 180, height: 180 },
        { width: 192, height: 192 },
        { width: 512, height: 512 },
        { width: 1024, height: 1024 },
      ],
      resizeOptions: { fit: "contain", background: "#2E3440" },
    },
  },
  images: "static/pictures/logo.png",
});
