/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as LinkhubIndexRouteImport } from './routes/linkhub/index'
import { Route as ImpressumIndexRouteImport } from './routes/impressum/index'
import { Route as CvIndexRouteImport } from './routes/cv/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as AboutmeIndexRouteImport } from './routes/aboutme/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkhubIndexRoute = LinkhubIndexRouteImport.update({
  id: '/linkhub/',
  path: '/linkhub/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumIndexRoute = ImpressumIndexRouteImport.update({
  id: '/impressum/',
  path: '/impressum/',
  getParentRoute: () => rootRouteImport,
} as any)
const CvIndexRoute = CvIndexRouteImport.update({
  id: '/cv/',
  path: '/cv/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutmeIndexRoute = AboutmeIndexRouteImport.update({
  id: '/aboutme/',
  path: '/aboutme/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aboutme': typeof AboutmeIndexRoute
  '/contact': typeof ContactIndexRoute
  '/cv': typeof CvIndexRoute
  '/impressum': typeof ImpressumIndexRoute
  '/linkhub': typeof LinkhubIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aboutme': typeof AboutmeIndexRoute
  '/contact': typeof ContactIndexRoute
  '/cv': typeof CvIndexRoute
  '/impressum': typeof ImpressumIndexRoute
  '/linkhub': typeof LinkhubIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aboutme/': typeof AboutmeIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/cv/': typeof CvIndexRoute
  '/impressum/': typeof ImpressumIndexRoute
  '/linkhub/': typeof LinkhubIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aboutme'
    | '/contact'
    | '/cv'
    | '/impressum'
    | '/linkhub'
    | '/projects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aboutme'
    | '/contact'
    | '/cv'
    | '/impressum'
    | '/linkhub'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/aboutme/'
    | '/contact/'
    | '/cv/'
    | '/impressum/'
    | '/linkhub/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutmeIndexRoute: typeof AboutmeIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  CvIndexRoute: typeof CvIndexRoute
  ImpressumIndexRoute: typeof ImpressumIndexRoute
  LinkhubIndexRoute: typeof LinkhubIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkhub/': {
      id: '/linkhub/'
      path: '/linkhub'
      fullPath: '/linkhub'
      preLoaderRoute: typeof LinkhubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum/': {
      id: '/impressum/'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv/': {
      id: '/cv/'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aboutme/': {
      id: '/aboutme/'
      path: '/aboutme'
      fullPath: '/aboutme'
      preLoaderRoute: typeof AboutmeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutmeIndexRoute: AboutmeIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  CvIndexRoute: CvIndexRoute,
  ImpressumIndexRoute: ImpressumIndexRoute,
  LinkhubIndexRoute: LinkhubIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
